# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: build:go
    - task: bundle:cps
    - task: prerender:frontend
    - task: copy:root

  generate:
    dir: packages/server
    cmds:
      - go generate ./...
    sources:
      - internal/pkg/graph/schema.grahqls
      - internal/pkg/graph/resolver.go
    generates:
      - internal/pkg/graph/schema.resolver.go
      - internal/pkg/graph/generated/generated.go
      - internal/pkg/graph/model/models_gen.go

  build:go:
    dir: packages/server
    deps: [generate]
    cmds:
      - go build -o dist/{{.OUTPUT}} cmd/server/server.go
      - go build -o dist/{{.OUTPUT}} cmd/update/update.go
    sources:
      - cmd/**
      - internal/**
    generates:
      - dist/server
      - dist/update
  build:go:windows:
    dir: packages/server
    deps: [generate]
    cmds:
      - go build -o dist/server.exe cmd/server/server.go
      - go build -o dist/update.exe cmd/update/update.go
    env:
      GOOS: "windows"
    sources:
      - cmd/**
      - internal/**
    generates:
      - dist/server.exe
      - dist/update.exe

  bundle:cps:
    dir: packages/addon
    sources:
      - src/functions/**
      - src/procedures/**
      - src/**
      - scripts/bundle
    generates:
      - dist/AddOn.cps.xml
    cmds:
      - scripts/bundle

  prerender:frontend:
    generates:
      - packages/frontend/dist
    sources:
      - packages/frontend/!dist
    cmds:
      - yarn frontend prerender

  copy:root:
    sources:
      - packages/*/dist/**
      - packages/server/default-config.yaml
    generates:
      - dist/**
    cmds:
      - cp -a packages/addon/dist/. dist/
      - cp -a packages/server/dist/. dist/
      - cp -a packages/server/default-config.yaml dist/.wc.yaml
      - cp -a packages/frontend/dist/driverscreen/browser dist/public/
