on: push

name: Release Addon

jobs:
  build:
    name: Release Addon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - run: yarn install
      - name: Build project
        run: |
          task generate
          task build:go:windows
          task bundle:cps
          task prerender:frontend
          task copy:root
      - name: Zip Assets
        run: |
          cp README.md dist
          cd dist
          zip "../dist" -r ./** ./.* -e .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Addon Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: graphql-addon-${{ github.ref }}.zip
          asset_content_type: application/zip
